# Generated by Django 4.2.5 on 2023-09-20 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0005_crearusuario_delete_curso_delete_entregable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='autor_nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
